### ISSUE TITLE
Conflict with Automated Animations

### ISSUE THREAD

**Issue by XtraButtery** [ZotyDev/objects-interactions-fx#1]
```
Active Modules:
----------
Automated Animations v;
Automated Objects, Interactions and Effects v;
Item Piles v;
JB2A - Patreon Complete Collection v;
libWrapper v0;
Midi QOL v;
Sequencer v;
socketlib v;
Tidy UI - Game Settings v;
```

When [Automated Animations](https://github.com/otigon/automated-jb2a-animations) is installed **and enabled**, animations that are also integrated into Automated Animation will play twice.

As Automated Animations offers better customisation for individual weapons, allows for other types of animations (such as AoE spells, and auras) and is generally the preferred method of using J2BA's animations it may be better to try and hook into its configurations and code to make it a dependency rather than hardcoding specific animations into certain weapon tags. Especially as you already appear to be lifting parts of their code to make your animations work already.

**Comment by XtraButtery** [comment]
To further develop this idea, it would also allow you to remove certain redundant tags, and potentially the entire dependency on Tagger.

Currently you utilise tags to assign a particular animation to an object _and_ determine whether or not it is a thrown weapon, but if you were instead integrating with Automated Animations you would be able to simply utilise weapon properties within the 5E system you could simply check to see if the weapon is considered to be a thrown weapon, making the end-user experience much more streamlined.

![image](https://user-images.githubusercontent.com/35461692/179303565-886d85c9-ee19-4d93-a345-00764edf2a7e.png)

**Comment by ZotyDev** [comment]
Hey, thanks for the feedback. Yeah, I was expecting something like this conflict with AA happening, actually I've never used AA before. Will take a look and find a smooth way of handling this, but probably will disable the animations that AA already take care of. Tagger is, tbh, just used to set a lighting tag on the token holding a lighting item, shouldn't be a hard requirement.

**Comment by ZotyDev** [comment]
Hi! Sorry for ceasing to exist for some months, this is currently fixed e.e
The fix, alongside MANY additions will be on the next release, probably this weekend.
My approach was to provide a way to toggle animations, currently thinking on how to integrate this with Automated Animations perfectly. (Item drops on miss are not synced with AA animations, kinda impossible rn but I will find a fix)
![image](https://user-images.githubusercontent.com/34866157/216784875-31728f9b-14cf-4c30-960a-0bb214296d72.png)

**Comment by KellethDregar** [comment]
Hi! Really liking this model but can't really bring myself to use it due to the conflict with automated animations. Is there any progress on this?

**Comment by ZotyDev** [comment]
Yes, currently the only thing that does not work perfectly is the sync between where AA effects land and the creation of a ItemPile, for now I will make it be created on a random border of the target token.

**Comment by KellethDregar** [comment]
@ZotyDev How do you remove the doubled up animations? I currently do not see the options you showed above 

![image](https://user-images.githubusercontent.com/79947702/230767628-a3027b7e-ff55-4996-8337-0d0d7f65b950.png)
