### ISSUE TITLE
[BUG]: Thrown/Ammunition Items Not Creating Item Piles on miss 

### ISSUE THREAD

**Issue by KellethDregar** [ZotyDev/objects-interactions-fx#15]
### Browsers

Chrome

### What Happened?

When a thrown or ammunition weapon attack misses it will not create an item pile. It will go into the target tokens inventory it seems. Can confirm it still works in version 1.0.2 but broke after that point.

![image](https://user-images.githubusercontent.com/79947702/233603546-c9777acf-89c0-45c1-b57f-8cd690a071f1.png)

### Reproduction Steps

```bash
1. Set so thrown items create item in target inventory on hit and item pile on miss
2. Use a ranged weapon with tags (dagger) to attack a target
3. On miss it will correctly be placed in the target inventory, on miss however it will also be placed in their inventory even if it should've become an item pile
```

### Relevant Log Output

```Shell
No relevant output on the logs since this is a normal behavior it's just happening on the wrong condition.
```

**Comment by ZotyDev** [comment]
Hi! Thanks for reaching out!
This is a data collection bug that is related to MdiQOL (not their problem, I did something wrong). I'm currently investigating and will update and fix as soon as possible.
Sorry for this inconvenience.
