### ISSUE TITLE
[BUG]: Ammunition Break Chance

### ISSUE THREAD

**Issue by Neakas** [ZotyDev/objects-interactions-fx#18]
### Discord Username

Neakas

### Browsers

Native Foundry Client

### What Happened?

No matter what setting i input for the Ammunition break Chance, no breaking occurs.
Even at 100% Break chance, the item pile is still beeing created if missed and an Item is added to the target inventory if hit.

the fault seems to be at:
ItemAnimator Line 326. for Ranged Attacks. I havent tested thrown Weapons, but since the code is identical im guessing those dont work either.

### Reproduction Steps

```bash
1.Set break Chance to 100%
2.Attack a Target
3.Item never breaks
```

**Comment by ZotyDev** [comment]
Hi! Thanks for reaching out! Yes you are correct the error is at the random chance function.
Fix will be included on the next update.
