### ISSUE TITLE
Item Pile appears before animation is finished.

### ISSUE THREAD

**Issue by XtraButtery** [ZotyDev/objects-interactions-fx#2]
As can be seen in your own preview the item pile appears at the start of the animation rather than on the impact.

![image](https://github.com/ZotyDev/objects-interactions-fx/raw/main/images/thrown_miss.gif)

Other modules such as TheRipper93's Splatter module recommend a delay of 1750ms in order to have elements appear in sync with J2BA's animations.

Adding this slight delay would increase the visual appeal of the module, which appears to be an overall goal for the project given the maul's integration causing the screen to shake.

**Comment by ZotyDev** [comment]
Should be fixed on the next release, thansk for reporting that.
![thrown_miss](https://user-images.githubusercontent.com/34866157/179337843-67c42735-4d83-4e95-8791-ba1d00c43d6b.gif)
