### ISSUE TITLE
[BUG]: V11 compatibility

### ISSUE THREAD

**Issue by apoapostolov** [ZotyDev/objects-interactions-fx#22]
### Discord Username

ApoApostolov#4622

### Browsers

Chrome

### What Happened?

V11 cannot initialize the canvas when the mod is active. Probably no compatibility yet

### Reproduction Steps

```bash
Install V11
Activate Mod
See no canvas
```

**Comment by ZotyDev** [comment]
Thanks for reaching out about the incompatibility! V11 will be the new supported version when v2.0.0 comes out.

**Comment by ZotyDev** [comment]
It was surprisingly easy to do it, just removed one line! Thanks again for reaching out :D
