### ISSUE TITLE
[BUG]:  Error on hooked function for hook midi-qol.AttackRollComplete

### ISSUE THREAD

**Issue by thatlonelybugbear** [ZotyDev/objects-interactions-fx#29]
### Discord Username

thatlonelybugbear

### Browsers

Chrome, Edge

### What Happened?

The issue is that for spell type Items (and others probably), the `item.system.properties` is `undefined`.
The module doesn't seem to take that into account (when MidiQOL is active).

Simple changes needed 
```js
system:
  {
    name: 'dnd5e',
    meleeWeaponDistance: canvas.dimensions.distance,
    normalDistance: Item.system.range.value,
    longDistance: Item.system.range.long,
    isThrowable: Item.system.properties?.thr || false,    
    //or just Item.system.properties?.thr etc depending on how it's used later on
    isConsumeAmmo: Item.system.properties?.amm || false,
    ammoItem: Item.system.consume?.target || false,   //maybe this too
  },
  ```

### Reproduction Steps

```bash
Just roll an item that doesn't have any of the checked properties.
```

**Comment by ZotyDev** [comment]
Thanks for reporting this bug! I've fixed it just now, thanks for taking your time to make a complete and very helpful report!
