### ISSUE TITLE
Option for item pile create after attack roll. 

### ISSUE THREAD

**Issue by JonathanEspinosaLong** [ZotyDev/objects-interactions-fx#3]
I'd like to see an option for the item pile to be created after the attack roll finishes and Midi QOL detects that it misses. From what I can tell the item pile is created after the damage roll complete. That is ok if you have full automation running but in my case I don't. So if my attack misses I still need to roll damage for the item pile to be created.

**Comment by ZotyDev** [comment]
Will take a look into that, new version will be a major improvement and include it.

**Comment by ZotyDev** [comment]
Hey, sorry for taking so long.
This is fixed on v0.2
