### ISSUE TITLE
[SYSTEM]: PF1E

### ISSUE THREAD

**Issue by winkles99** [ZotyDev/objects-interactions-fx#35]
### Discord Username

sgtbun

### System

https://gitlab.com/foundryvtt_pathfinder1e/foundryvtt-pathfinder1

### Notes on the Support

I'm running 1E for a group of players for this first time, and this would be a great module to have! Thanks for all your hard work!

**Comment by ZotyDev** [comment]
Duplicate of #13, please follow the other issue for updates on the support.
