### ISSUE TITLE
Add option to make item pile conversions snap to grid

### ISSUE THREAD

**Issue by PlasticMohawk** [ZotyDev/objects-interactions-fx#4]
Nice module! It should be possible to round off the coordinates of where the item pile is created (for example, a thrown dagger that misses) to conform to the grid settings of whatever scene the action is happening on. This may present a cleaner interface for those of us that like to have everything stackenblocken.

Thanks!

**Comment by ZotyDev** [comment]
Hey, thanks for the suggestion. Will add it on the next release.
