### ISSUE TITLE
[SUGGESTION] Item Pile on Hit

### ISSUE THREAD

**Issue by 9ryex5** [ZotyDev/objects-interactions-fx#7]
Just as you have a setting to "Create Item Piles on Miss" can you add another one to "Create Item Piles on Hit"?
![image](https://user-images.githubusercontent.com/43207603/228826807-2e0cc3c2-4e95-4d66-8d95-0c8a3e5a5c6c.png)

**Comment by ZotyDev** [comment]
Thanks for the suggestion! This will be added on the next release.
